sites:
    sitenow.uiowa.edu:
        type: custom
        site: uiowa701
        git: 'git@github.com:ITS-UofIowa/sitenow.uiowa.edu.git'
        profile: sitenow
    chemsafe.lab.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    davies.lab.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    aac.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    aaup.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    acm.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    alphaupsilonlambdas.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    amnesty.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    anthropology.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    apalsa.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    apo.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    arh.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    arthistory.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    asa.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    asauiowa.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    badminton.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    bars.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    blackart.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    blsa.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    campadventure.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    cec.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    china.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    cmaedu.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    cssa.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    cycling.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    designui.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    dic.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    drupal.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    edoncampus.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    english-society.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    epx.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    evaluation.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    faith.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    fcc.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    ghs.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    gradmed.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    hawkeyeoptimistchapter.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    helpinghawks.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    herkycares.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    i3hsa.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    ieee.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    iowawomensclubvolleyball.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    isea.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    itsonus.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    kusa.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    lgbtqsf.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    medicus.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    mindfulatiowa.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    mssui.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    ncte.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    nicaragua.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    nofrills2015.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    ocf.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    ostem.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    pls.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    productdesignstudio.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    pso.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    roco.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    rowing.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    rugby.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    runningc.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    shpe.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    sigmaalphaiota.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    sinfonia.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    sipe.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    sls.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    soundtoword16.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    spectrumui.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    star.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    studentsindesign.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    tkd.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    trihawks.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    turkish.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    uibestbuddies.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    uiems.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    uienvironmentalcoalition.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    uimsa.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    uinasa.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    uiphotography.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    uira.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    uirobotics.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    uisug.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    uitransalliance.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    veterans.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    womensicehockey.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
