sites:
    apalsa.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    arh.org.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    chemsafe.lab.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
    davies.lab.uiowa.edu:
        type: standard
        site: uiowa701
        profile: sitenow_standard_profile
