sudo: false

language: php

php:
  - 5.6

matrix:
  fast_finish: true

before_install:
  - composer self-update

install:
  # Install dependencies.
  - composer install

script:
  - lint-yaml .sites.yml
